"""update quiz

Revision ID: c74a62d6c04f
Revises: 1cc89f2d6e32
Create Date: 2025-07-02 12:30:44.785766

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c74a62d6c04f"
down_revision: str | None = "1cc89f2d6e32"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quizzes", sa.Column("explanation", sa.String(length=200), nullable=True)
    )
    op.add_column("quizzes", sa.Column("user_id", sa.BigInteger(), nullable=False))
    op.create_foreign_key(
        "fk_quiz_user", "quizzes", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_quiz_user", "quizzes", type_="foreignkey")
    op.drop_column("quizzes", "user_id")
    op.drop_column("quizzes", "explanation")
    # ### end Alembic commands ###
